### ISSUE TITLE
the customer would be also newbie to Eclipse, better indicate which file to add these lines.

### ISSUE THREAD

**Issue by xiaodongliang** [jaimerosales/forge.learning-1#10]
the customer would be also newbie to Eclipse, better indicate which file to add these lines.
<img width="801" alt="screen shot 2018-04-05 at 1 58 07 pm" src="https://user-images.githubusercontent.com/5087461/38400448-a650bc10-3982-11e8-8cd8-58a436101a57.png">

**Comment by jaimerosales** [comment]
Ok I removed this, makes more sense to set the Targeted Runtime which will add this to the POM.xml file.
