### ISSUE TITLE
I got error that ‘clean’ is not defined. It worked after I switch to ‘Maven Clean’.

### ISSUE THREAD

**Issue by xiaodongliang** [jaimerosales/forge.learning-1#12]
I got error that ‘clean’ is not defined. It worked after I switch to ‘Maven Clean’.

<img width="581" alt="screen shot 2018-04-05 at 2 00 56 pm" src="https://user-images.githubusercontent.com/5087461/38400608-77f95c86-3983-11e8-8d50-823595553695.png">

**Comment by jaimerosales** [comment]
The Screen shot in the tutorial has been updated, you need to run "clean install" in the goals of the build
