### ISSUE TITLE
where to find 'server>>add and remove'...?

### ISSUE THREAD

**Issue by xiaodongliang** [jaimerosales/forge.learning-1#13]
<img width="624" alt="screen shot 2018-04-05 at 2 01 38 pm" src="https://user-images.githubusercontent.com/5087461/38400864-f0e70480-3984-11e8-9fa6-c67e1d8e4ebf.png">
I had no idea where to find Server, finally, I made the server working as below (right-click the solution, and choose Run As…). As you can see, the app is running within Eclipse. I do not even need to go browser.

<img width="704" alt="screen shot 2018-04-05 at 2 02 31 pm" src="https://user-images.githubusercontent.com/5087461/38400902-13d9de7c-3985-11e8-9eb3-b1e497425dd9.png">

**Comment by jaimerosales** [comment]
Change the way to invoke the server on first time, followed your suggestions, I also notice I had typos.
