### ISSUE TITLE
After adding all configuration, two errors with pom.xml 

### ISSUE THREAD

**Issue by xiaodongliang** [jaimerosales/forge.learning-1#15]
<img width="547" alt="screen shot 2018-04-05 at 2 13 25 pm" src="https://user-images.githubusercontent.com/5087461/38400955-609d23c2-3985-11e8-84ce-45b29b64c4e3.png">

After adding all configuration, two errors with pom.xml 

_Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:build-helper-maven-plugin:1.10:add-source (execution: add_sources, phase: generate-sources)_ 

It requires to follow the error hints to install the latest m2e.

**Comment by jaimerosales** [comment]
I took this POM from your Intellij one, we might want to dive deep to figure out what exactly we need then.

**Comment by jaimerosales** [comment]
Ok I replaced the one I just made work!
