### ISSUE TITLE
 the issue when access serverlet endpoint. 

### ISSUE THREAD

**Issue by xiaodongliang** [jaimerosales/forge.learning-1#17]
the building runs well, the main page is also opened, but when trying to access the endpoint of getting token, it failed. I hit the issue when access serverlet endpoint. It should be no classes is not output. Not yet got where to set… 

<img width="791" alt="screen shot 2018-04-05 at 3 32 55 pm" src="https://user-images.githubusercontent.com/5087461/38401663-aa810e32-3989-11e8-946f-31f3d366da84.png">

**Comment by jaimerosales** [comment]
still working on this, funny how my other server works fine and I'm doing the same setup still breaking my head with this. :)

**Comment by jaimerosales** [comment]
You need to do this, since right now it is serving from /forgesample and all the endpoints will be serving from '/' 

![screen shot 2018-04-06 at 7 25 00 pm](https://user-images.githubusercontent.com/8932722/38448165-529a01be-39d0-11e8-87ef-02bb2b112fca.png)

**Comment by xiaodongliang** [comment]
this does not h help my side.  Finally, I made it working by ticking the following options: Project>>Properties>>JAVA Build Path

<img width="680" alt="screen shot 2018-04-08 at 9 38 01 pm" src="https://user-images.githubusercontent.com/5087461/38468185-3348274a-3b75-11e8-94fd-27bd2481b4cf.png">

**Comment by jaimerosales** [comment]
I think we are not having issues with this anymore, if it persist please reopen.
