### ISSUE TITLE
package should be removed

### ISSUE THREAD

**Issue by xiaodongliang** [jaimerosales/forge.learning-1#19]
if we keep the same structure such as main>>java>>*.java, the new class should ignore package name. Otherwise, the final structure will be main>>java>>**packagename**>>*.java

<img width="770" alt="screen shot 2018-04-08 at 9 31 53 pm" src="https://user-images.githubusercontent.com/5087461/38468124-622855d6-3b74-11e8-813f-30907614b78b.png">

**Comment by jaimerosales** [comment]
Needs more testing.

**Comment by jaimerosales** [comment]
Mentioned in create server steps.
