### ISSUE TITLE
IntelliJ Ultimate IDE (not-free)

### ISSUE THREAD

**Issue by augustogoncalves** [jaimerosales/forge.learning-1#2]
isn't there any other alternative that is free? Or is there a significant benefit with this IDE?

I'm asking as other tutorials are using free IDEs, which are good enough for beginners

**Comment by augustogoncalves** [comment]
have you considered Visual Code? 
https://code.visualstudio.com/docs/languages/java

FYI: the Go extension works just fine, [Denis is using](https://github.com/apprentice3d/forge.learning/blob/go/docs/environment/tools/go.md)  and here is a GIF on to install it:

![](https://github.com/apprentice3d/forge.learning/raw/go/docs/_media/go/install_go_extension.gif)

**Comment by jaimerosales** [comment]
Switched to Eclipse.
