### ISSUE TITLE
Switch to PORT 3000 instead of 8080

### ISSUE THREAD

**Issue by jaimerosales** [jaimerosales/forge.learning-1#24]

**Comment by augustogoncalves** [comment]
this is just in preparation for 3-legged samples, note that on [Create an App](http://learnforge.autodesk.io/#/account/?id=create-an-app) we used `: 3000` and this is standard (or almost standard) on our samples. 

the [.NET tutorial](http://learnforge.autodesk.io/#/environment/setup/net?id=port) changes that too, Visual Studio (for .NET) uses a "random" port number.

**Comment by jaimerosales** [comment]
Fixed and gif for setup added
