### ISSUE TITLE
Tomcat 8 end-of-life

### ISSUE THREAD

**Issue by augustogoncalves** [jaimerosales/forge.learning-1#26]
> Users of Tomcat 8.0.x should be aware that the Tomcat team have announced the end of life date for Tomcat 8.0.x. Users of Tomcat 8.0.x should plan to upgrade before Tomcat 8.0.x reaches end of life.

This is your link: https://tomcat.apache.org/download-80.cgi

Should your tutorial point to v9?

**Comment by jaimerosales** [comment]
Tomcat 9 works fine. Will switch to use that instead
