### ISSUE TITLE
Misplaced image

### ISSUE THREAD

**Issue by augustogoncalves** [jaimerosales/forge.learning-1#6]
at **/modelderivative/translate/java** this image shows the UI files, which are not created at this point: **/_media/java/IntelliJ-IDEA-project_all_files_server.png**

![image](https://user-images.githubusercontent.com/4291593/37472948-08997f62-284c-11e8-886e-a8dcc35ffaf6.png)

the image is correctly used at **/viewer/java**

(same sizing issue with this image, see #1 )

**Comment by jaimerosales** [comment]
No longer using this.
